alpha:
  #  graylogHost=${GRAYLOG_HOST}
  #  graylogPort=${GRAYLOG_PORT}

  data-source:
    jdbcUrl: jdbc:mysql://${ALPHA_PRIMARY_DB_HOST}:${ALPHA_PRIMARY_DB_PORT}/${ALPHA_PRIMARY_DB_NAME}?autoReconnect=true
    username: ${ALPHA_PRIMARY_DB_USER_NAME}
    password: ${ALPHA_PRIMARY_DB_PASSWORD}
    autoCommit: false
    connectionTimeout: 600000
    maxLifetime: 3600000
    idleTimeout: 600000
    connectionTestQuery: select 2+2;
    minimumIdle: 10
    maximumPoolSize: 20
    poolName: alpha-pool
    leakDetectionThreshold: 50000
    initialize: false

    # whether to generate unique name for the data source
    generateUniqueName: false

    # the name of the data source
    name: ${ALPHA_PRIMARY_DB_USER_NAME}
    databaseName: ${ALPHA_PRIMARY_DB_NAME}

  primaryDatabaseName: ${ALPHA_PRIMARY_DB_NAME}
  redisHostName: ${ALPHA_REDIS_HOST}
  redisPort: ${ALPHA_REDIS_PORT}
  redisActive: ${ALPHA_REDIS_ACTIVE}
  tokenExpiryTime: ${ALPHA_TOKEN_EXPIRY_TIME}
  tokenExpiryTimeUnit: ${ALPHA_TOKEN_EXPIRY_TIME_UNIT}
  otpExpiryTime: ${ALPHA_OTP_EXPIRY_TIME}
  otpExpiryTimeUnit: ${ALPHA_OTP_EXPIRY_TIME_UNIT}

#spring:
#  mail:
#    host: ${SMTP_HOST}
#    port: ${SMTP_PORT}
#    username: ${SMTP_USERNAME}
#    password: ${SMTP_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#            required: true
#          auth: true
#          connectiontimeout: 10000
#          timeout: 10000
#          writetimeout: 10000
